version: '3'
services:
  db:
    container_name: db-mysql
    build:
      context: .
      dockerfile: ./server/dockerfile.mysql 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SMART-MANAGEMENT
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 15
    volumes:
      - ./server/database/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    ports:
      - "3306:3306"
    networks:
      - app-network
  backend:
    container_name: app-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app-network
  frontend:
    container_name: app-frontend
    build:
      context: ./reactjs
      dockerfile: Dockerfile
    volumes:
      - ./reactjs:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge