version: '3'
services:
  db:
    container_name: db-mysql
    build:
      context: .
      dockerfile: ./server/dockerfile.mysql 
    command: 
      - mysqld
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - ./server/database/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    ports:
      - "3306:3306"
  backend:
    container_name: app-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    command: ["/bin/sh", "-c", "./wait-for-it.sh db 3306 && npm start"]
    depends_on:
      - db
    ports:
      - "3000:3000"
  frontend:
    container_name: app-frontend
    build:
      context: ./reactjs
      dockerfile: Dockerfile
    volumes:
      - ./reactjs:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    command: ["npm", "start"]